# Generated by Django 4.2.5 on 2023-09-28 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_useraccount_is_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pretrials',
            old_name='text',
            new_name='case_act',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_user',
            new_name='is_client',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='pretrials',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.CharField(max_length=255)),
                ('chamber_address', models.TextField(blank=True, null=True)),
                ('lawyer_type', models.PositiveSmallIntegerField(choices=[('1', 'Civil'), ('2', 'Criminal'), ('3', 'Family'), ('4', 'Corporate')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__created_at',),
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.CharField(max_length=255)),
                ('court_address', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__created_at',),
            },
        ),
    ]
