# Generated by Django 4.2.5 on 2023-09-28 18:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_text_pretrials_case_act_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_act', models.TextField()),
                ('details', models.TextField(blank=True, null=True)),
                ('date_registered', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PreTrial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_registered',),
            },
        ),
        migrations.DeleteModel(
            name='PreTrials',
        ),
    ]
