# Generated by Django 4.2.5 on 2023-09-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pretrial_delete_pretrials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_judge',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_lawyer',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('LAWYER', 'Lawyer'), ('JUDGE', 'Judge')], default='CLIENT', max_length=50, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='bar_code',
            field=models.CharField(max_length=255, verbose_name='Bar council code for judges'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='court_address',
            field=models.TextField(blank=True, null=True, verbose_name='Court Address for judges'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='bar_code',
            field=models.CharField(max_length=255, verbose_name='Bar council code for lawyers'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='chamber_address',
            field=models.TextField(blank=True, null=True, verbose_name='Chamber address for lawyers'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='lawyer_type',
            field=models.CharField(choices=[('CIVIL', 'Civil'), ('CRIMINAL', 'Criminal'), ('FAMILY', 'Family'), ('CORPORATE', 'Corporate')], default='CIVIL', max_length=50, verbose_name='Lawyer Types'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address of the User'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Boolean definining active status'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Boolean definining staff access level'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Boolean definining staff access level'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of the User'),
        ),
    ]
