# Generated by Django 4.2.5 on 2023-09-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_useraccount_is_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyer',
            old_name='lawyer_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_type',
            new_name='type',
        ),
    ]
